version: '3.3'
services:
   db:
     container_name: 'local-wordpress-db'
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - 18766:3306
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: mydatabase
   wordpress:
     container_name: 'local-wordpress'
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8765:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 'db:3306'
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: mydatabase
     volumes:
       - "./wordpress:/var/www/html"
       - "./plugins:/var/www/html/wp-content/plugins"
volumes:
    db_data: {}